name: swiift
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.3.1
  smooth_page_indicator: ^1.0.0
  firebase: ^9.0.3
  sizer: ^2.0.15
  flutter_screenutil: ^5.8.4
  flutter_svg: ^1.0.3
  blobs: ^2.0.0
  firebase_remote_config: ^3.0.15
  firebase_analytics: ^10.1.6
  firebase_crashlytics: ^3.0.17
  firebase_messaging: ^14.3.0
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  cloud_functions: ^4.0.13
  firebase_storage: ^11.0.16
  firebase_database: ^10.0.16
  firebase_app_check: ^0.1.1
  cloud_firestore: ^4.4.5
  firebase_performance: ^0.9.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
     - assets/swiiftlogo.png
     - assets/delivery.json
     - assets/onboardingimg.jpeg
     - assets/money.json
     - assets/greenimg.json
     - assets/google.png
     - assets/apple.png
     - assets/loginbackground.jpg
     - assets/blob.svg
     - assets/goodsblack.svg
     - assets/blackmotorcycle.svg
     - assets/blackmotorcycle.png
     - assets/moneyblack.png
     - assets/loader.json

     
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
