name: swiift
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.3.1
  smooth_page_indicator: ^1.0.0
  sizer: ^2.0.15
  flutter_screenutil: ^5.8.4
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
     - assets/swiiftlogo.png
     - assets/delivery.json
     - assets/onboardingimg.jpeg
     - assets/money.json
     - assets/greenimg.json
     - assets/google.png
     - assets/apple.png
     - assets/loginbackground.jpg

     
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
