
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSA6x2heQhMKZxBvoo2uXNB5pgt_IXXwE',
    authDomain: 'swiift-hq-c97f0.firebaseapp.com',
    projectId: 'swiift-hq-c97f0',
    storageBucket: 'swiift-hq-c97f0.appspot.com',
    messagingSenderId: '717542303333',
    appId: '1:717542303333:web:9e303c1f43e8f6fc0ac88c',
    measurementId: 'G-BBWG4G1TF9'
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpLSgmJitBQIoKSYYvOWop89caP191NwQ',
    iosBundleId: 'com.android.application',
    appId: '1:717542303333:ios:f427c8546f88b4c00ac88c',
    storageBucket: 'swiift-hq-c97f0.appspot.com',
    messagingSenderId: '717542303333',
    iosClientId: 'undefined',
    projectId: 'swiift-hq-c97f0'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjrqG8kr1ETlCMJciMLLwzk7n1w8rYum4',
    appId: '1:717542303333:android:71ad3e2dc58554e60ac88c',
    messagingSenderId: '717542303333',
    projectId: 'swiift-hq-c97f0',
    storageBucket: 'swiift-hq-c97f0.appspot.com'
  );
}
